[package]
name = "fox-chess-proc"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full", "visit-mut"] }

[lib]
proc-macro = true
